#####################################################################
# Docker Compose File for launching containers services
# Author: Theppasith N. <tutorgaming@gmail.com>
# Date: 6-May-2023
#####################################################################
version: '2.0'
services:
  main:
    container_name: torch-tutor
    image: tutorgaming/pytorch-docker:latest
    build: .
    environment:
      - JUPYTER_TOKEN=obodroid
      - TERM=xterm-256color
    volumes:
      # HOST:CONTAINER
      - ${HOME}/Repository/workspace:/workspace # Workspace Path for Codes
      - ${HOME}/Datasets:/workspace/Datasets:ro # Dataset Folder Path : Read-Only
      - ${HOME}/Datasets:/root/Datasets
    ports:
      # HOST:CONTAINER
      - 8080:8888 # JupyterLab
      - 6006:6006 # Tensorboard
    deploy:
      resources:
        reservations:
          devices:
            # Enable Nvidia Docker
            - driver: nvidia
              count: all
              capabilities: [gpu]
