#####################################################################
# Docker Compose File for launching containers services
# Author: Theppasith N. <tutorgaming@gmail.com>
# Date: 6-May-2023
#####################################################################
version: '2.0'
services:
  main:
    container_name: torch-tutor                     # Running Container Name
    image: tutorgaming/pytorch-docker:latest        # After build Image Name
    build: .                                        # Where's "Dockerfile"
    environment:
      - JUPYTER_TOKEN=obodroid                      # Jupyter Password
      - TERM=xterm-256color                         # Colored Terminal
    volumes:
      # HOST:CONTAINER
      - ${HOST_WORKSPACE_PATH}:/workspace           # Workspace Path for Codes
      - ${HOST_DATASET_PATH}:/workspace/Datasets:ro # Dataset Folder Path : Read-Only
    ports:
      # HOST:CONTAINER
      - 8080:8888 # JupyterLab
      - 6006:6006 # Tensorboard
    deploy:
      resources:
        reservations:
          devices:
            # Enable Nvidia Docker
            - driver: nvidia
              count: all
              capabilities: [gpu]
